[book]
title = "RISC-V Crypto: Исследование и реализация"
authors = ["Фролов Кирилл", "Мирошниченко Лев"]
language = "ru"
multilingual = false
src = "src"

[build]
create-missing = false

[output.html]
no-section-label = true

[output.html.playground]
runnable = false
